certificate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("", include("web_app.urls"))]

web_app/urls.py
from django.urls import path
from web_app.views.authentication_views import (
    EditProfileView,
    LoginView,
    LogoutView,
    ProfileView,
)

from web_app.views.certificate_views import (
    CertificateSearchView,
    CertificateView,
    LandingView,
)

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path(
        "create/",
        login_required(CertificateView.as_view(), login_url="/login"),
        name="create",
    ),
    path(
        "search/",
        login_required(CertificateSearchView.as_view(), login_url="/login"),
        name="search",
    ),
    path("", login_required(LandingView.as_view(), login_url="/login"), name="landing"),
    path(
        "profile/",
        login_required(ProfileView.as_view(), login_url="/login"),
        name="profile",
    ),
    path(
        "edit-profile/",
        login_required(EditProfileView.as_view(), login_url="/login"),
        name="edit-profile",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

web_app/models.py
import os
from django.db import models
from versatileimagefield.fields import VersatileImageField
from nepali_datetime import date
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser
from django.db.models.signals import post_save
from django.dispatch import receiver

from .managers import UserManager


class GenderChoices(models.TextChoices):
    male = ("male", "Male")
    female = ("female", "Female")


class User(AbstractBaseUser, PermissionsMixin):
    objects = UserManager()

    avatar = models.ImageField(upload_to="profile/", blank=True)
    username = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["password"]

    @property
    def get_full_name(self):
        return self.first_name + " " + self.last_name


class Institute(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    institute_name = models.CharField(max_length=100, blank=True)
    institute_logo = models.ImageField(upload_to="logos/", blank=True)
    institute_address = models.CharField(max_length=100, blank=True)


# Create your models here.
class Certificate(models.Model):
    school_name = models.CharField(max_length=200)
    school_address = models.CharField(max_length=200)
    established_date = models.CharField(max_length=200)
    gender = models.CharField(max_length=200, choices=GenderChoices.choices)
    student_name = models.CharField(max_length=200)
    student_fathers_name = models.CharField(max_length=200)
    student_address = models.CharField(max_length=200)
    academic_year = models.CharField(max_length=200)
    program = models.CharField(max_length=200)
    passed_year = models.CharField(max_length=200)
    secured_gpa = models.CharField(max_length=200)
    date_of_birth = models.DateField()
    symbol_number = models.CharField(max_length=200)
    registration_number = models.CharField(max_length=200, unique=True)
    issued_date = models.CharField(
        max_length=200, default=date.today().__str__(), null=True
    )
    exam_board = models.CharField(max_length=30, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    certificate = VersatileImageField(upload_to="media/", null=True)

    def __str__(self) -> str:
        return self.registration_number


@receiver(post_save, sender=User)
def create_institute(sender, instance, created, **kwargs):
    if created:
        Institute.objects.create(user=instance)


# @receiver(post_save, sender=User)
# def save_institute(sender, instance, created, **kwargs):
#     if created:
#         superuser = User.objects.filter(is_superuser=True).first()
#         instance.institute.institute_name = superuser.institute.institute_name
#         instance.institute.institute_logo = superuser.institute.institute_logo
#         instance.institute.institute_address = superuser.institute.institute_address

#         instance.institute.save()

# @receiver(post_save, sender=User)
# def update_institute(sender, instance, **kwargs):
#     institutes = Institute.objects.filter(user=instance)
#     superuser = User.objects.filter(is_superuser=True).first()

#     for institute in institutes:
#         institute.institute_name = superuser.institute.institute_name
#         institute.institute_logo = superuser.institute.institute_logo
#         institute.institute_address = superuser.institute.institute_address

#         institute.save()

web_app/views.py
import base64
import os
from django.shortcuts import render
from django.views import View

from web_app.models import Certificate

from .forms import CertificateForm, CertificateSearch
from web_app.utils.util import create_certificate


class LandingView(View):
    def get(self, request):
        return render(request, "landing.html")
# Create your views here.
class CertificateView(View):
    form = CertificateForm

    def get(self, request):
        form = self.form()
        return render(request, "index.html", {"form": form})

    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            new_model = form.save()
            create_certificate(
                form.cleaned_data["school_name"],
                form.cleaned_data["school_address"],
                form.cleaned_data["established_date"],
                form.cleaned_data["gender"],
                form.cleaned_data["student_name"],
                form.cleaned_data["student_fathers_name"],
                form.cleaned_data["student_address"],
                form.cleaned_data["academic_year"],
                form.cleaned_data["program"],
                form.cleaned_data["passed_year"],
                form.cleaned_data["secured_gpa"],
                form.cleaned_data["date_of_birth"],
                form.cleaned_data["symbol_number"],
                form.cleaned_data["registration_number"],
                form.cleaned_data["issued_date"],
            )
            new_model.certificate = (
                f"media/certificate_{form.cleaned_data['registration_number']}.png"
            )
            new_model.save()

            with open(
                f"media/certificate_{form.cleaned_data['registration_number']}.png",
                "rb",
            ) as f:
                data = base64.b64encode(f.read()).decode("utf-8")

            ctx = {"image": data, "form": form}

            return render(request, "image.html", ctx)
        return render(request, "index.html", {"form": form})


class CertificateSearchView(View):
    form = CertificateSearch

    def get(self, request):
        form = self.form
        return render(request, "search.html", {"form": form})

    def post(self, request):
        form = self.form(request.POST)
        try:
            with open(
                f"media/certificate_{form.data.get('registration_number')}.png", "rb"
            ) as f:
                data = base64.b64encode(f.read()).decode("utf-8")

            ctx = {"image": data, "form": form}

            return render(request, "image.html", ctx)
        except Exception:
            form.add_error("registration_number", "Invalid registration number")
            pass
        return render(request, "search.html", {"form": form})

web_app/views/authentication_views.py
from django.views import View
from django.shortcuts import render, redirect
from web_app.forms import LoginUserForm, ProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from web_app.models import User


class LoginView(View):
    form = LoginUserForm

    def get(self, request):
        form = self.form()
        return render(request, "login.html", {"form": form})

    def post(self, request):
        form = self.form(request.POST)
        username = form.data.get("username")
        password = form.data.get("password")
        remember_me = form.data.get("remember_me")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if not remember_me:
                request.session.set_expiry(0)
            messages.success(request, "Logged in successfully!")
            return redirect("/")
        form.add_error("password", "Invalid username or password")

        return render(request, "login.html", {"form": form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, "Logged out successfully!")
        return redirect("/login")


class ProfileView(View):
    def get(self, request):
        return render(request, "profile.html")


class EditProfileView(View):
    form = ProfileForm

    def get(self, request):
        form = self.form()
        return render(request, "edit_profile.html", {"form": form})

    def post(self, request):
        form = self.form(request.POST, request.FILES)
        if form.is_valid():
            user = User.objects.get(username=request.user.username)
            user.first_name = form.data.get("first_name")
            user.last_name = form.data.get("last_name")
            if institute_name := form.data.get("institute_name"):
                user.institute.institute_name = institute_name
            if institute_address := form.data.get("institute_address"):
                user.institute.institute_address = institute_address
            if logo := request.FILES.get("institute_logo"):
                user.institute.institute_logo = logo
            if avatar := request.FILES.get("avatar"):
                user.avatar = avatar
            user.save()
            user.institute.save()
            messages.success(request, "Your profile is updated successfully")
            return redirect(to="profile")

        return render(request, "edit_profile.html", {"form": form})

web_app/views/certificate_views.py
import base64
import os
from django.shortcuts import render
from django.views import View
from ..models import Certificate
from os.path import exists
from django.db import transaction
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


from ..forms import CertificateForm, CertificateSearch
from web_app.utils.util import create_certificate


class LandingView(View):
    def get(self, request):
        if not request.user.is_superuser:
            certificate_list = Certificate.objects.filter(
                user_id=request.user.id
            ).order_by("student_name")
        else:
            certificate_list = Certificate.objects.all().order_by("student_name")
        paginator = Paginator(certificate_list, 5)
        page_number = request.GET.get("page")
        try:
            certificates = paginator.get_page(page_number)
        except PageNotAnInteger:
            certificates = paginator.page(1)
        except EmptyPage:
            certificates = paginator.page(paginator.num_pages)
        return render(request, "landing.html", {"certificates": certificates})


class CertificateView(View):
    form = CertificateForm

    def get(self, request):
        form = self.form()
        return render(request, "index.html", {"form": form})

    @transaction.atomic
    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            new_model = form.save()
            new_model.user_id = request.user.id
            certificate_path = (
                f"certificate_{form.cleaned_data['registration_number']}.jpg"
            )
            create_certificate(
                request.user,
                form.cleaned_data["school_name"] or "",
                form.cleaned_data["school_address"]
                or request.user.institute.institute_address,
                form.cleaned_data["established_date"],
                form.cleaned_data["gender"],
                form.cleaned_data["student_name"],
                form.cleaned_data["student_fathers_name"],
                form.cleaned_data["student_address"],
                form.cleaned_data["academic_year"],
                form.cleaned_data["program"],
                form.cleaned_data["passed_year"],
                form.cleaned_data["secured_gpa"],
                form.cleaned_data["date_of_birth"],
                form.cleaned_data["symbol_number"],
                form.cleaned_data["registration_number"],
                new_model.issued_date,
                form.cleaned_data["exam_board"],
            )
            new_model.certificate = certificate_path
            new_model.save()

            with open(
                f"media/{certificate_path}",
                "rb",
            ) as f:
                data = base64.b64encode(f.read()).decode("utf-8")

            ctx = {
                "image": data,
                "form": form,
                "title": "image",
                "filename": certificate_path,
            }

            return render(request, "image.html", ctx)
        return render(request, "index.html", {"form": form})


class CertificateSearchView(View):
    form = CertificateSearch

    def get(self, request):
        form = self.form
        return render(request, "search.html", {"form": form})

    def post(self, request):
        form = self.form(request.POST)
        certificate_path = f"certificate_{form.data.get('registration_number')}.jpg"
        if not request.user.is_superuser:
            model = Certificate.objects.filter(
                registration_number=form.data.get("registration_number"),
                user_id=request.user.id,
            )
        else:
            model = Certificate.objects.filter(
                registration_number=form.data.get("registration_number")
            )
        if not model.exists():
            try:
                os.system(f"rm media/{certificate_path}")
            except Exception:
                pass
        if model.exists() and not exists(f"media/{certificate_path}"):
            data = model.first()
            create_certificate(
                request.user,
                data.school_name,
                data.school_address or request.user.institute.institute_address,
                data.established_date,
                data.gender,
                data.student_name,
                data.student_fathers_name,
                data.student_address,
                data.academic_year,
                data.program,
                data.passed_year,
                data.secured_gpa,
                data.date_of_birth,
                data.symbol_number,
                data.registration_number,
                data.issued_date,
                data.exam_board,
            )

        if model.exists():
            try:
                with open(f"media/{certificate_path}", "rb") as f:
                    data = base64.b64encode(f.read()).decode("utf-8")

                ctx = {
                    "image": data,
                    "form": form,
                    "filename": certificate_path,
                }

                return render(request, "image.html", ctx)
            except Exception:
                form.add_error("registration_number", "Invalid registration number")
                pass

        form.add_error("registration_number", "Invalid registration number")
        return render(request, "search.html", {"form": form})

web_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.js"
      integrity="sha512-CX7sDOp7UTAq+i1FYIlf9Uo27x4os+kGeoT7rgwvY+4dmjqV0IuE/Bl5hVsjnQPQiTOhAX1O2r2j5bjsFBvv/A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"
    />
    <link
      rel="stylesheet"
      href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      href="http://nepalidatepicker.sajanmaharjan.com.np/nepali.datepicker/css/nepali.datepicker.v4.0.min.css"
      rel="stylesheet"
      type="text/css"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% if not request.user.institute.institute_name and request.user.is_authenticated and not 'edit-profile' in request.path and not request.user.institute.institute_logo %}
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Update your Profile</h5>
          <a href="{% url 'logout' %}"><button type="button" class="close" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </a>
        </div>
        <div class="modal-body">
          It looks like you haven't updated your profile. Please update your profile and continue.
        </div>
        <div class="modal-footer">
          <a href="{% url 'edit-profile' %}"><button type="button" class="btn btn-primary">Update Profile</button></a>
          <a href="{% url 'logout' %}"><button type="button" class="btn btn-secondary">Close</button></a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
    {% if 'login' not in request.path %}
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'landing' %}">
        {% if request.user.institute.institute_logo %}
        <img
          src="/media/{{request.user.institute.institute_logo}}"
          width="30"
          height="30"
          alt=""
          class="d-inline-block align-top"
        />
        {% endif %} CCMS
      </a>

      <div class="row">
        <div class="col-sm-12 text-center">
          {% if request.user.is_staff or request.user.is_superuser %}
          <a href="/admin"
            ><button class="btn btn-primary btn-md">Admin</button></a
          >
          {% endif %} {% if request.user.is_authenticated %}
          <a href="{% url 'profile' %}"
            ><button class="btn btn-success btn-md">Profile</button></a
          >
          <a href="{% url 'logout' %}"
            ><button class="btn btn-outline-secondary btn-md text-white">
              Logout
            </button></a
          >
          {% else %}
          <a href="{% url 'login' %}"
            ><button class="btn btn-primary btn-md">Login</button></a
          >
          {% endif %}
        </div>
      </div>
    </nav>
    {% endif %} {% block content %} {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script
      src="http://nepalidatepicker.sajanmaharjan.com.np/nepali.datepicker/js/nepali.datepicker.v4.0.min.js"
      type="text/javascript"
    ></script>
    {% for message in messages %}
    <script>
      alertify.set("notifier", "position", "bottom");
      alertify.success("{{message}}");
    </script>
    {% endfor %}
    <script type="text/javascript">
      $(window).on("load", function(){
        $('#exampleModalCenter').modal('show')
      });
    </script>
  </body>
</html>

web_app/templates/edit_profile.html
{% extends 'base.html' %} 
{% block title %} Create Certificate {% endblock %} 
{%block content %}
<section class="vh-100">
    <div class="container py-5 h-100">
      <div class="row justify-content-center align-items-center h-100">
        <div class="col-12 col-lg-9 col-xl-7">
          <div
            class="card shadow-2-strong card-registration"
            style="border-radius: 15px"
          >
            <div class="card-body p-4 p-md-5">
              <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">
                Edit Profile
              </h3>
  
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
  
                <div class="row">
                  <div class="col-md-6 mb-2">
                      <div class="form-outline">
                        <label class="form-label" for="firstName"
                          >First Name</label
                        >
                      {{form.first_name}} {{form.first_name.errors}}
  
                    </div>
                  </div>
                  <div class="col-md-6 mb-2">
                      <label class="form-label" for="lastName"
                        >Last Name</label
                      >
                    <div class="form-outline">
                      {{form.last_name}} {{form.last_name.errors}}
                    </div>
                  </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-2">
                        <div class="form-outline">
                          <label class="form-label" for="firstName"
                            >Institute Name</label
                          >
                        {{form.institute_name}} {{form.institute_name.errors}}
    
                      </div>
                    </div>
                      <div class="col-md-6 mb-2">
                          <label class="form-label" for="lastName"
                            >Institute Address</label
                          >
                        <div class="form-outline">
                          {{form.institute_address}} {{form.institute_address.errors}}
                        </div>
                      </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6 mb-2">
                        <label class="form-label" for="lastName"
                          >Avatar</label
                        >
                      <div class="form-outline">
                        {{form.avatar}} {{form.avatar.errors}}
                      </div>
                    </div>
                      <div class="col-md-6 mb-2">
                          <label class="form-label" for="lastName"
                            >Institute Logo</label
                          >
                        <div class="form-outline">
                          {{form.institute_logo}} {{form.institute_logo.errors}}
                        </div>
                      </div>
                </div>
                <div class="mt-4 pt-2">
                    <input
                      class="btn btn-primary btn-lg"
                      type="submit"
                      value="Save"
                      method="post"
                    />
                    <a href="{% url 'landing' %}"
                      ><button class="btn btn-primary btn-lg" type="button">
                        Back
                      </button></a
                    >
                  </div>
            </form>
            </div>
        </div>  
    </div>
</div>
</div>
  </section>
<script type="text/javascript">
  function validateImageType(){
    var file = $("#id_institute_logo").val();
    var idxDot = file.lastIndexOf(".") + 1;
    var extension = file.substr(idxDot, file.length).toLowerCase();
    if(!(extension == "png")){
      alert("Only png files are allowed!");
      $(location.reload());
    }
  }
</script>
{% endblock %}

web_app/templates/image.html
<center>
  <img src="data:image/jpg;base64,{{ image }}" height="961" width="1354" />
</center>
<a download="{{ filename }}" href="data:image/jpg;base64,{{ image }}"
  >Download</a
>
<a href="{% url 'search' %}">Back</a>

web_app/templates/landing.html
{% extends 'base.html' %} {% block title %} Generate Certificate {% endblock %}
{% block content %}
<div class="px-4 py-5 my-5 text-center">
  {% if request.user.avatar %}
  <img src="/media/{{request.user.avatar}}" alt="avatar"
                class="rounded-circle img-fluid" style="width: 150px;">
  {% endif %}
  <h2 class="display-5 fw-bold">Hi, {{request.user.username | capfirst}}!</h2>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">Welcome to Character Certificate Management System</p>
    <div class="d-grid gap-5 d-sm-flex justify-content-sm-center">
      <a href="{% url 'create' %}"
        ><button class="btn btn-primary btn-lg px-4 me-sm-3 mb-4 mr-3">
          Create Certificate
        </button></a
      >
      <a href="{% url 'search' %}"
        ><button class="btn btn-outline-secondary btn-lg px-4 mr-3">
          Search Certificate
        </button></a
      >
    </div>
  </div>
  {% if certificates %}
  <hr>
<div class="text-center">
  <h3>List of Certificates</h3>
  </div>
<div class="row justify-content-center">
  <div class="col-auto">
    <table class="table table-responsive">
      <thead>
        <tr>
            <th>Registration Number</th>
            <th>Student's Name</th>
            <th>Certificate</th>
        </tr>
    </thead>
    <tbody>
      {% for certificate in certificates %}
      <tr>
      <td>{{certificate.registration_number}}</td>
      <td>{{certificate.student_name}}</td>
      <td><a download="{{certificate.certificate}}" href="/media/{{certificate.certificate}}">Download</a>
        <a target="_blank" href="/media/{{certificate.certificate}}">Show</a>
      </td>
    </tr>
      {% endfor %}
    </tbody>
    </table>
    {% endif %}
    {% if certificates.has_other_pages %}
    <div class="btn-group" role="group" aria-label="Item pagination">
        {% if certificates.has_previous %}
            <a href="?page={{ certificates.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
        {% endif %}

        {% for page_number in certificates.paginator.page_range %}
            {% if certificates.number == page_number %}
                <button class="btn btn-outline-primary active">
                    <span>{{ page_number }} <span class="sr-only">(current)</span></span>
                </button>
            {% else %}
                <a href="?page={{ page_number }}" class="btn btn-outline-primary">
                    {{ page_number }}
                </a>
            {% endif %}
        {% endfor %}

        {% if certificates.has_next %}
            <a href="?page={{ certificates.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
        {% endif %}
    </div>
    {% endif %}
</div>
</script>
{% if 'login' not in request.path%}
<footer
  class="text-center text-lg-start bg-light text-muted mt-auto fixed-bottom"
>
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05)">
    Developed with ❤️ by © BNS
  </div>
</footer>
{% endif %} {% endblock %}

web_app/templates/login.html
{% extends 'base.html' %}
{% block title %} Login -  Certificate Generator {% endblock %}
{% block content %}
<section class="vh-100 text-center">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <h3 class="mb-5">Login</h3>
            <form method="post" class="form-signin">
              {% csrf_token %}
            <div class="form-outline mb-4">
                <label class="form-label" for="typeEmailX-2">Username</label>
                {{form.username}}{{form.username.errors}}              
            </div>

            <div class="form-outline mb-4">
                <label class="form-label" for="typePasswordX-2">Password</label>
                {{form.password}}{{form.password.errors}}
            </div>

            <!-- Checkbox -->
            <div class="form-check d-flex justify-content-start mb-4">
              {{form.remember_me}}
              <label class="form-check-label" for="form1Example3"> Remember me </label>
            </div>

            <button class="btn btn-primary btn-lg btn-block" type="submit" method="post">Login</button>

            <!-- <hr class="my-4"> -->

            <!-- <button class="btn btn-lg btn-block btn-primary" style="background-color: #dd4b39;"
              type="submit"><i class="fab fa-google me-2"></i> Sign in with google</button>
            <button class="btn btn-lg btn-block btn-primary mb-2" style="background-color: #3b5998;"
              type="submit"><i class="fab fa-facebook-f me-2"></i>Sign in with facebook</button> -->

          </div>
      </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

web_app/templates/search.html
{% extends 'base.html' %} {% block title %} Search Certificate 
{% endblock %} 
{% block content %}
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-lg-9 col-xl-7">
        <div
          class="card shadow-2-strong card-registration"
          style="border-radius: 15px"
        >
          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">
              Search Character Certificate
            </h3>

            <form method="post">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-12 mb-4">
                  <div class="form-outline">
                    {{form.registration_number}}
                    {{form.registration_number.errors}}

                    <label class="form-label" for="firstName"
                      >Registration Number</label
                    >
                  </div>
                </div>
              </div>
              <div>
                <input
                  class="btn btn-primary btn-lg"
                  type="submit"
                  value="Submit"
                  method="post"
                />
                <a href="{% url 'landing' %}"
                  ><button class="btn btn-primary btn-lg" type="button">
                    Back
                  </button></a
                >
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}